# .github/workflows/dev.yml
name: Standalone CLI

on: [push, pull_request]

jobs:
  machineStandalone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222
      - name: machineStandalone
        uses: docker://docker.io/fluidattacks/cli:latest
        with:
          args: skims scan Fix/config.yaml
      - name: Upload Fluid-Attacks-Results.csv
        uses: actions/upload-artifact@v3
        with:
          name: Fluid-Attacks-Results
          path: Fluid-Attacks-Results.csv
